minecraft@chonk:~$ cat server.properties
#Minecraft server properties
#Tue Mar 24 11:16:44 MDT 2026
accepts-transfers=true
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=https\://github.com/devsecfranklin/game-server-minecraft/issues/new/choose
debug=false
difficulty=normal
enable-code-of-conduct=true
enable-command-block=true
enable-jmx-monitoring=false
enable-query=true
enable-rcon=true
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=default
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=k1wsrmJZh77vQr7l049eDnCyi2wMkj5TsFLhNEju
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-build-height=256
max-chained-neighbor-updates=1000000
max-players=69
max-tick-time=-1
max-world-size=29999984
motd=§6Dreamland §7| §fEst. 2012
network-compression-threshold=256
online-mode=true
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
previews-chat=false
pvp=false
query.port=25555
rate-limit=0
rcon.password=dinosaurExTraVaGanZa1969%%
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25566
simulation-distance=12
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=64
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
tnt-explosions=true
use-native-transport=true
view-distance=10
white-list=false

