name: Bandit Security Scan

on:
  pull_request

jobs:
  bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        # -r: recursive, -ll: report only medium/high severity, -x: exclude tests
        run: bandit -r . -ll -f txt -o bandit-report.txt
        continue-on-error: true

      - name: Upload Security Report
        uses: actions/upload-artifact@v7
        with:
          name: bandit-security-report
          path: bandit-report.txt

